# Generated by Django 5.1.7 on 2025-03-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0002_post_header_image_post_snippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="snippet",
            field=models.CharField(default="", max_length=255),
        ),
    ]
