# Generated by Django 5.1.7 on 2025-03-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0006_remove_post_categories_post_categorie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="categorie",
            new_name="category",
        ),
    ]
